[ ] Okay, so the chapman stick lays out bass and melody courses 
    for the two hands to play, left hand playing the melody while
    right hand taps the bass.  But the notes still go from lowest
    at the "nut" to highest at the "bridge".  But we can make the
    frets work anyway we want, so why not put the lowest notes
    toward the thumb of the right hand and the little finger of
    the left hand.  Which would also suggest putting the bass
    on the left hand side and the treble on the right hand side.
[ ] If we can retune the midi note table, shouldn't be hard, then
    we can do 24-tet and 31-tet with chromatic fretting.  All that
    needs is a font with the half-flat and half-sharp characers.
[ ] All of these variations need to go into a database that can
    be exported and imported and edited as necessary.
[ ] All of the configuration options for the instrument should be
    remotely controllable from another phone/tablet/laptop via
    osc over websocket, this is how you tweak the string tone
    while playing.  The playing surface should be full screen and
    immune to most everything.  Set a gesture to escape back to
    the configuration screens.
[ ] Vibraphone model in modal bars, one of several presets for the
    instrument which need to be faustified to compile to wasm.
    It seems that the parameters could be bundled as a with clause
    or something, in any case made constant.  Vibraphone on a 
    fretboard could be outrageous, have to get some feedback on it.
[ ] https://ccrma.stanford.edu/~jos/pasp/pasp.html has the details
    on stiffness.  But the Faust physical models library guitar
    model uses a coefficient of nearly 0 for steel guitar, and 0.4
    for the nylon strings, so the filter may just be left out of the
    eks.
[ ] Pentatonic scales https://en.wikipedia.org/wiki/Pentatonic_scale
    5 modes of pentatonic: major, blues major, minor, blues minor, and
    suspended (aka egyptian!).  Also named in chinese and south asian
    traditions.
[ ] The user interface is being a total pain in the ass.  Using faust-ui
    conflicts with the normal lit-html construction practice.  Rewriting
    into zither-ui, using lit-html, yields massive failure to expand the
    ui.  Attempting to use shoelace-style components find that they are
    mysteriously crippled when they're intantiated inside one of my
    web components.  Works fine at the toplevel, fails to style when inside.
[ ] So, I can make a web page of bookmarks for zither.elf.org which
    launch differently configured instruments.  So all I need is to define
    the core search string parameters.
* parameters to zither
** tune - a list of notes - sets the number of strings and the notes they
   sound.
	could be a well known tuning as a string of note names: EADGBE, GDAE, etc.
	could be a comma separated list of midi note numbers
	could be a concatenated string or comma separated list of midi note names
** transpose - number of semitones to transpose up or down the tuning
** frets - the number of semitones implemented
** freting - a list of fret types per string, or one for all strings
	f - fretted - chromatically fretted
	u - unfretted - continuously tuned 
	o - open string only - pluckable harp, lyre, or zither string
	r - reverse fretted or unfretted from bridge toward nut
** scale - one of several predefined scale names
** tonic - the tonic note of the scale
** label-notes - visibly identify the notes at each fretting
	either as ABC..., or as solfege, absolute or relative
** color-notes - palette for coloring notes.
** hide-off-scale - off scale notes are not drawn - they are blank frets
** mute-off-scale - off scale notes are not drawn or played
** cover-off-scale - off scale notes are played as the next on scale note
** instrument parameters - numerical paramaters for the physical model
** effect parameters - numberical parameters for the effect model
