* The lowest notes of the low 8 string bass sound wrong, 
  they're all the same note for the first 8 notes on the
  two lowest strings.
** Tried increasing the Pmax in physicalmodels.lib, that
  seemed to help but only some.
** Went back to Smith's original eks.dsp, which has its
  own Pmax, but one which allows the bass notes.  Also
  seemed to help, but not that much.
** Compared to the notes generated by geoshred, but was
  somewhat confused by geoshred's octave offset.  My
  notes are buzzier, and almost entirely atonal buzz at
  the low end.
** So, what can it be?
*** A frequency bias in the excitation.
*** A frequency bias in the loop filter.
** Tried using no.pink_noise, no change.
** Tried using noise : lpf,
   with { lpf = (x + x')/2; }
   and it started to make a difference with 3 concatenated
   lpf blocks.
* I've updated to the latest @graem/faustwasm package
  and I'm getting the undefined class error in the async
  loading stream, where a series of classes are defined
  into temporary names and then copied to their correct
  global names.  Don't remember if I fixed that before of
  if it just went away.
  
